### ISSUE TITLE
Boilerplate

### ISSUE THREAD

**Issue by suwarno-ong** [mauritsd/react-native-dynamic-bundle#1]
Hi,

I tried the steps provided on the markdown.
`registerBundle('test', 'test.js');`
`setActiveBundle('test'); // does not work`

`getActiveBundle('test').then(data => {`
`    console.log(data); //printed as 'test'`
`    reloadBundle(); // does not work`
`})`

Is there anything I can troubleshoot? Do you have boilerplate for this?

I have verified that the test.js exists in Document directory.
`rnfs.readFile(``${rnfs.DocumentDirectoryPath}/test.js``)`
`   .then(data => {`
`     console.log(data);`
`   });`

Regards,
Suwarno

**Comment by mauritsd** [comment]
Hi,

Did you have a look at the example project? Are you on Android or iOS? 

I had some troubles getting this to work on Android while development mode is enabled, so you could try with a release build if you're on Android.

With regards,
Maurits

**Comment by suwarno-ong** [comment]
Oh yes, I just saw the example folder. I am able to load the bundle for iOS. However for android, the reloadBundle keep refreshing the screen. 

Will this work for react native 0.56?

**Comment by mauritsd** [comment]
I've not tried on recent RN versions yet, and there is a known issue with Android in development mode. As far as I know, RN, when running in dev mode on Android, will always load the bundle from the development server and will completely ignore any file-based JS bundles provided to it. You could try building the example as a release APK.

Of course the logic to do bundle reloading is only useful in production builds anyway, as you can simply test the revision you want to in dev mode. I'll update the docs to note that it doesn't (entirely) work on Android.

**Comment by suwarno-ong** [comment]
Ok thanks @mauritsd

**Comment by jdnichollsc** [comment]
Hi @mauritsd 
I'm reviewing from Android (release mode) but there's an issue after active a bundle:
- react-native run-android --variant=release
```
02-28 23:47:21.404 6141-6192/? E/ReactNativeJS: Module AppRegistry is not a registered callable module (calling unmountApplicationComponentAtRootTag)
```
- From the signed apk
```
03-01 00:14:05.008 23028-23047/? D/ReactNative: Initializing React Xplat Bridge.
03-01 00:14:05.009 23028-23047/? D/ReactNative: Initializing React Xplat Bridge before initializeBridge
03-01 00:14:05.015 23028-23047/? D/ReactNative: Initializing React Xplat Bridge after initializeBridge
    CatalystInstanceImpl.runJSBundle()
03-01 00:14:05.016 23028-23064/? D/ReactNative: ReactInstanceManager.setupReactContext()
    CatalystInstanceImpl.initialize()
03-01 00:14:05.017 23028-23064/? D/ReactNative: ReactInstanceManager.attachRootViewToInstance()
03-01 00:14:05.287 23028-23063/? E/ReactNativeJS: undefined is not a function (evaluating 'this._nativeModule.addListener(eventType)')
```
After that the app is closed all the time when I try to open it again

What do you think? This is the repo: https://github.com/proyecto26/react-native-modular/tree/dynamic-bundle
