### ISSUE TITLE
IOS: The new bundle does not load even after executing `reloadBundle()`

### ISSUE THREAD

**Issue by adkaushik** [mauritsd/react-native-dynamic-bundle#11]
React native version: 0.56, using this only for ios

I created a `main.jsbundle` file ( with some known visible changes in the home screen to identify the bundle) and hosted it on s3. Then, reverting those change and including `react0native-dynamic-bundle`, and the the code to dynamically change the js bundle, I created the main.jsbundle and ran the application in  release scheme.

So the main.jsbundle contains the code to dynamically change the bundle.

In the code, I used RNFS library to download and store the bundle in the documents directory of the simulator (followed the example exactly). I can see the downloaded bundle in the documents directory. 

However, when I run **`registerBundle('test', 'test.bundle')`**,  and then run **`setActiveBundle('test');`**, I see no change when the command **`reloadBundle()`** runs.
The screen does not reload (No splashscreen), and interestingly, the alert message that I have after **`reloadBundle()`** in the previous bundle (Alert('reloaded')) executes and I get an alert.

And When I use `react-native-restart` the app simply crashes in `main.m` at this line
`    return UIApplicationMain(argc, argv, nil, NSStringFromClass([AppDelegate class]));
`

Is this the expected result? How can I be sure that the bundle got updated? I don't think that this has worked for me. Please help.

```javascript
handleDynamicUpdate = async () => {
 
   const { promise } = RNFS.downloadFile({
    fromUrl: 'https://s3.eu-central-1.amazonaws.com/link-to-my-s3-bucket/main.jsbundle',
     toFile: `${RNFS.DocumentDirectoryPath}/test.bundle`,
   });

   const result = await promise;
 
   const activeBundle1 = await getActiveBundle();
   
    Alert.alert('before active bundle', activeBundle1);
   
    registerBundle('test', 'test.bundle');

    setActiveBundle('test');

    const activeBundle = await getActiveBundle();
    
    Alert.alert('bundles and active bundle ', activeBundle); // this prompts `test` as the active bundle

    Alert.alert('reloading');
    
     reloadBundle(); // Nothing happens 

    Alert.alert('reloaded'); // This line gets executed after reloading the bundle

  };
```

**Comment by mauritsd** [comment]
It could be that the library itself is not working as intended anymore on newer versions of RN. I'm in the process of updating everything to a new RN version and testing everything out. Unfortunately I don't have a lot of time during the week, but I'll see if I can spend some time fixing and testing it next weekend.

**Comment by mauritsd** [comment]
Wait, did you make the modifications in the native (iOS) code as well? You need to make small modifications to your AppDelegate.{m,h} as in the example.

https://github.com/mauritsd/react-native-dynamic-bundle/blob/master/example/ios/example/AppDelegate.m

https://github.com/mauritsd/react-native-dynamic-bundle/blob/master/example/ios/example/AppDelegate.h

If you want to know whether the reload is triggering correctly, you can put a logging statement in AppDelegate.m at line 37:

```objc
- (void)dynamicBundle:(RNDynamicBundle *)dynamicBundle requestsReloadForBundleURL:(NSURL *)bundleURL
{
  NSLog(@"Reloading bundle to URL: %@", bundleURL);
  self.window.rootViewController.view = [self getRootViewForBundleURL:bundleURL];
}
```

**Comment by adkaushik** [comment]
Sorry, I didn't know about the changes in the app delegate. I will check and get back.👍

**Comment by adkaushik** [comment]
Getting build error in `appdelegate.h`. Should we also include library search path?
```ObjC
'RNDynamicBundle.h' file not found
#import <RNDynamicBundle.h>
        ^~~~~~~~~~~~~~~~~~~
1 error generated.
```

**Comment by adkaushik** [comment]
@mauritsd, After making the changes in appdelegate, it works now. However, I also had to add Header Search path and set it to recursive to get it to working.

**Comment by adkaushik** [comment]
How should we revert to the main bundle (the original one) ? Should I again use the library to register the main bundle and then set it as active bundle?

**Comment by mauritsd** [comment]
You are able to return to the bundle that was packaged with the react native app by calling `setActiveBundle(null)` from the javascript side.
