### ISSUE TITLE
setActiveBundle has no effect. New bundle is not applying

### ISSUE THREAD

**Issue by chesovnik** [mauritsd/react-native-dynamic-bundle#13]
Hi!

I have implemented a dynamic bundle from the example, but it doesn't have any effect

```
System:
    OS: macOS 10.15.1
    CPU: (12) x64 Intel(R) Core(TM) i7-8850H CPU @ 2.60GHz
    Memory: 38.47 MB / 16.00 GB
    Shell: 5.7.1 - /bin/zsh
  Binaries:
    Node: 13.6.0 - /usr/local/bin/node
    Yarn: 1.21.1 - /usr/local/bin/yarn
    npm: 6.13.4 - /usr/local/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  SDKs:
    iOS SDK:
      Platforms: iOS 13.2, DriverKit 19.0, macOS 10.15, tvOS 13.2, watchOS 6.1
  IDEs:
    Android Studio: 3.5 AI-191.8026.42.35.6010548
    Xcode: 11.2.1/11B500 - /usr/bin/xcodebuild
  npmPackages:
    react: 16.8.3 => 16.8.3 
    react-native: ^0.60.4 => 0.60.5
```

**Comment by chesovnik** [comment]
Should we make any changes to ANDROID files (expect library linking), like we should do for iOS regarding to your [comment](https://github.com/mauritsd/react-native-dynamic-bundle/issues/11#issuecomment-534247854)?

**Comment by chesovnik** [comment]
Regarding to [this issue](https://github.com/mauritsd/react-native-dynamic-bundle/issues/1), I am testing in production mode on a real device

**Comment by chesovnik** [comment]
The issue was resolved by:
1) Modifying  MainActivity.java / MainApplication.java as in the Example.
2) Fetching the last package version from Git.

**Comment by Arjunmore6673** [comment]
> The issue was resolved by:
> 
> 1. Modifying  MainActivity.java / MainApplication.java as in the Example.
> 2. Fetching the last package version from Git.

I'm getting same issue im running example provided by this library and passing my new bundle, app is showing bundle is activated after calling getActiveBundle. but not showing any content showing same screen after calling reloadBundle().
