### ISSUE TITLE
unable to execute the new bundle 

### ISSUE THREAD

**Issue by jaiminp21** [mauritsd/react-native-dynamic-bundle#2]
Hi ,
I have deployed the bundle on remote the server.
I am giving path as remote url in your example. remote bundle gets loaded but it not executing. Please let me know am I missing something ?

One more I want to load my bundle at the start of the application. Please give one sample example. 

Thank you !

**Comment by jdnichollsc** [comment]
+1

**Comment by mauritsd** [comment]
The library will not download the new bundle over HTTP for you, you'll have to do that yourself. For example with RNFS.downloadFile, like in the example.

**Comment by jdnichollsc** [comment]
@jaiminp21 as we can see here https://github.com/mauritsd/react-native-dynamic-bundle/blob/master/example/App.js#L52
