### ISSUE TITLE
Multiple bundles

### ISSUE THREAD

**Issue by jdnichollsc** [mauritsd/react-native-dynamic-bundle#3]
Hi Maurits!

Is it possible to have multiple bundles at the same time?

Thanks, Juan

**Comment by mauritsd** [comment]
Hi Juan,

Yes, that's definitely possible, although you can only have one active at a time, of course. You can call registerBundle() multiple times, and call getBundles() to see which bundles you currently have registered.

**Comment by jdnichollsc** [comment]
ohh I understand, only one active. Does each module have to have an AppRegistry.registerComponent, right?

**Comment by adkaushik** [comment]
@jdnichollsc can you please elaborate this? `Does each module have to have an AppRegistry.registerComponent, right?`
